% MMSE / Wiener Filter Lab - Version 1
% Real-valued case, filter length N = 3
%
% This script loads R and P generated by Python and verifies
% the Wiener-Hopf solution in MATLAB.
%
% Theory:
%   y(n) = W^T X(n)
%   e(n) = d(n) - y(n)
%   xi = E[e^2(n)]
%   Wopt = R^{-1} P
%
% Numerically, we solve:
%   R Wopt = P
%
% using MATLAB's backslash operator.

clear; clc; close all;

% Locate project root assuming this file is inside matlab/
currentFile = mfilename('fullpath');
[matlabDir, ~, ~] = fileparts(currentFile);
rootDir = fileparts(matlabDir);
dataDir = fullfile(rootDir, 'data');

% Load data
R = readmatrix(fullfile(dataDir, 'R_matrix.csv'));
P = readmatrix(fullfile(dataDir, 'P_vector.csv'));
x = readmatrix(fullfile(dataDir, 'input_signal.csv'));
d = readmatrix(fullfile(dataDir, 'desired_signal.csv'));

% Make sure P is a column vector
P = P(:);

% Filter length
N = 3;

% Solve Wiener-Hopf equation
W_matlab = R \ P;

% Rebuild X matrix from x
numSamples = length(x);
X = [];

for n = N:numSamples
    X = [X; x(n), x(n-1), x(n-2)];
end

d_valid = d(N:end);

% Compute output and error
y = X * W_matlab;
e = d_valid - y;

% MSE calculations
mse = mean(e.^2);
Ed2 = mean(d_valid.^2);
xi_min_formula = Ed2 - P.' * W_matlab;

% Save MATLAB weights
writematrix(W_matlab, fullfile(dataDir, 'weights_matlab.csv'));

% Display results
disp('MMSE Wiener Filter Lab - MATLAB Verification');
disp('-------------------------------------------');

disp('Autocorrelation matrix R:');
disp(R);

disp('Cross-correlation vector P:');
disp(P);

disp('Estimated Wiener weights from MATLAB:');
disp(W_matlab);

fprintf('MSE from actual error:      %.8f\n', mse);
fprintf('MMSE formula Ed2 - P^T W:   %.8f\n', xi_min_formula);

% Plot desired signal and filter output
figure;
plot(d_valid, 'LineWidth', 1.0);
hold on;
plot(y, '--', 'LineWidth', 1.0);
grid on;
xlabel('Sample index');
ylabel('Amplitude');
title('Desired signal d(n) vs Wiener filter output y(n)');
legend('Desired signal d(n)', 'Filter output y(n)');

% Plot error
figure;
plot(e, 'LineWidth', 1.0);
grid on;
xlabel('Sample index');
ylabel('Error amplitude');
title('Estimation error e(n) = d(n) - y(n)');